import type { KnowledgeBase } from "./types";

export type KnowledgeBaseFileAsset = {
  id: string;
  fileName: string;
  fileType: "docx" | "xlsx" | "pdf" | "png" | "jpg" | "mp4";
  description: string | null;
  sourceUnit: string;
  reporter: string;
  reportTime: string;
  updateFrequency: "daily" | "weekly" | "monthly" | "irregular";
  issueDate: string;
  lastUpdated: string;
  visibility: string;
  kbType: "unit" | "theme";
  fileCategory: "work_report" | "meeting_minutes";
  governanceStatus: "pending" | "processing" | "success";
};

export const knowledgeBaseListMock: KnowledgeBase[] = [
  {
    id: "kb-decision-001",
    title: "决策库",
    lastUpdated: "2026-03-20 14:30:00",
    description: "汇集总书记重要讲话批示文件、党中央决策部署文件、市委工作要求、区委工作安排等",
    visibility: "完全公开",
    itemCount: 45,
    type: "decision",
    tags: ["决策库"],
  },
  {
    id: "kb-001",
    title: "区大数据局",
    lastUpdated: "2026-03-18 09:12:20",
    description: "汇集区大数据局业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 18,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-002",
    title: "区发改委",
    lastUpdated: "2026-03-18 09:15:43",
    description: "汇集区发改委业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 16,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-003",
    title: "区文旅委",
    lastUpdated: "2026-03-18 09:18:06",
    description: "汇集区文旅委业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 14,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-004",
    title: "区住建委",
    lastUpdated: "2026-03-18 09:23:11",
    description: "汇集区住建委业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 12,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-005",
    title: "区交通局",
    lastUpdated: "2026-03-18 09:28:52",
    description: "汇集区交通局业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 20,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-006",
    title: "区教委",
    lastUpdated: "2026-03-18 09:33:09",
    description: "汇集区教委业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 22,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-007",
    title: "区卫健委",
    lastUpdated: "2026-03-18 09:37:24",
    description: "汇集区卫健委业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 11,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-008",
    title: "区市场监督管理局",
    lastUpdated: "2026-03-18 09:41:58",
    description: "汇集区市场监督管理局业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 13,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-009",
    title: "区生态环境局",
    lastUpdated: "2026-03-18 09:46:36",
    description: "汇集区生态环境局业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 17,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-010",
    title: "区人社局",
    lastUpdated: "2026-03-18 09:51:04",
    description: "汇集区人社局业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 15,
    type: "unit",
    unitCategory: "department",
    tags: ["单位库"],
  },
  {
    id: "kb-011",
    title: "渝州路街道",
    lastUpdated: "2026-03-18 10:05:17",
    description: "汇集渝州路街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 28,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-012",
    title: "石桥铺街道",
    lastUpdated: "2026-03-18 10:11:49",
    description: "汇集石桥铺街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 26,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-013",
    title: "二郎街道",
    lastUpdated: "2026-03-18 10:18:03",
    description: "汇集二郎街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 30,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-014",
    title: "杨家坪街道",
    lastUpdated: "2026-03-18 10:25:12",
    description: "汇集杨家坪街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 24,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-015",
    title: "黄桷坪街道",
    lastUpdated: "2026-03-18 10:32:45",
    description: "汇集黄桷坪街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 19,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-016",
    title: "谢家湾街道",
    lastUpdated: "2026-03-18 10:39:21",
    description: "汇集谢家湾街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 21,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-017",
    title: "石坪桥街道",
    lastUpdated: "2026-03-18 10:46:08",
    description: "汇集石坪桥街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 18,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-018",
    title: "中梁山街道",
    lastUpdated: "2026-03-18 10:53:34",
    description: "汇集中梁山街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 22,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-019",
    title: "九龙街道",
    lastUpdated: "2026-03-18 11:01:15",
    description: "汇集九龙街道业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 20,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-020",
    title: "华岩镇",
    lastUpdated: "2026-03-18 11:08:42",
    description: "汇集华岩镇业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 25,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-021",
    title: "陶家镇",
    lastUpdated: "2026-03-18 11:15:29",
    description: "汇集陶家镇业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 23,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-022",
    title: "西彭镇",
    lastUpdated: "2026-03-18 11:22:56",
    description: "汇集西彭镇业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 27,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-023",
    title: "铜罐驿镇",
    lastUpdated: "2026-03-18 11:30:18",
    description: "汇集铜罐驿镇业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 16,
    type: "unit",
    unitCategory: "town",
    tags: ["单位库"],
  },
  {
    id: "kb-024",
    title: "重庆九龙城市开发集团有限公司",
    lastUpdated: "2026-03-18 11:37:45",
    description: "汇集重庆九龙城市开发集团有限公司业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 32,
    type: "unit",
    unitCategory: "soe",
    tags: ["单位库"],
  },
  {
    id: "kb-025",
    title: "重庆九龙现代产业发展集团有限公司",
    lastUpdated: "2026-03-18 11:45:12",
    description: "汇集重庆九龙现代产业发展集团有限公司业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 29,
    type: "unit",
    unitCategory: "soe",
    tags: ["单位库"],
  },
  {
    id: "kb-026",
    title: "重庆九龙城乡运营集团有限公司",
    lastUpdated: "2026-03-18 11:52:38",
    description: "汇集重庆九龙城乡运营集团有限公司业务流程、工作规范、制度文件等资料",
    visibility: "组织内公开",
    itemCount: 31,
    type: "unit",
    unitCategory: "soe",
    tags: ["单位库"],
  },
  {
    id: "kb-027",
    title: "16912事项库",
    lastUpdated: "2026-03-19 10:05:17",
    description: "围绕16912事项汇集政策依据、办理流程、责任分工与典型案例",
    visibility: "完全公开",
    itemCount: 28,
    type: "theme",
    tags: ["主题库"],
  },
  {
    id: "kb-028",
    title: "重大事项库",
    lastUpdated: "2026-03-19 10:11:49",
    description: "围绕重大事项汇集政策依据、推进机制、协同流程与经验案例",
    visibility: "组织内公开",
    itemCount: 26,
    type: "theme",
    tags: ["主题库"],
  },
  {
    id: "kb-029",
    title: "重大项目库",
    lastUpdated: "2026-03-19 10:18:03",
    description: "围绕重大项目汇集政策依据、项目全周期流程、节点模板与案例",
    visibility: "完全公开",
    itemCount: 30,
    type: "theme",
    tags: ["主题库"],
  },
];

export const knowledgeBaseFileListMock: KnowledgeBaseFileAsset[] = [
  {
    id: "file-001",
    fileName: "部门简介",
    fileType: "docx",
    description: "区大数据局部门职能及组织架构介绍",
    sourceUnit: "区大数据发展管理局",
    reporter: "张三",
    reportTime: "2026-03-16 14:20:35",
    updateFrequency: "irregular",
    issueDate: "2023-12-01 09:00:00",
    lastUpdated: "2026-03-16 14:20:35",
    visibility: "组织内公开",
    kbType: "unit",
    fileCategory: "work_report",
    governanceStatus: "success",
  },
  {
    id: "file-002",
    fileName: "工作体系架构图",
    fileType: "png",
    description: null,
    sourceUnit: "区大数据发展管理局",
    reporter: "张三",
    reportTime: "2026-03-15 18:05:22",
    updateFrequency: "irregular",
    issueDate: "2023-11-15 10:30:00",
    lastUpdated: "2026-03-15 18:05:22",
    visibility: "组织内公开",
    kbType: "unit",
    fileCategory: "meeting_minutes",
    governanceStatus: "processing",
  },
  {
    id: "file-003",
    fileName: "核心业务",
    fileType: "pdf",
    description: "数字政府核心业务流程及规范文档",
    sourceUnit: "区大数据发展管理局",
    reporter: "赵刚",
    reportTime: "2026-03-17 09:12:48",
    updateFrequency: "monthly",
    issueDate: "2023-10-20 14:15:00",
    lastUpdated: "2026-03-17 09:12:48",
    visibility: "组织内公开",
    kbType: "unit",
    fileCategory: "work_report",
    governanceStatus: "pending",
  },
  {
    id: "file-004",
    fileName: "特色优势",
    fileType: "xlsx",
    description: null,
    sourceUnit: "区大数据发展管理局",
    reporter: "李伟",
    reportTime: "2026-03-12 11:30:17",
    updateFrequency: "weekly",
    issueDate: "2023-09-10 11:00:00",
    lastUpdated: "2026-03-12 11:30:17",
    visibility: "指定部门可见",
    kbType: "unit",
    fileCategory: "meeting_minutes",
    governanceStatus: "processing",
  },
  {
    id: "file-005",
    fileName: "标志性成果打造情况",
    fileType: "docx",
    description: "2024年度标志性成果建设进展与成效汇总",
    sourceUnit: "区大数据发展管理局",
    reporter: "刘洋",
    reportTime: "2026-03-11 16:44:05",
    updateFrequency: "monthly",
    issueDate: "2023-08-25 08:45:00",
    lastUpdated: "2026-03-11 16:44:05",
    visibility: "组织内公开",
    kbType: "theme",
    fileCategory: "work_report",
    governanceStatus: "success",
  },
];
